backend:
  name: github
  repo:  oxfordstudentguide/oxfordstudentguide.github.io
  branch: master # Branch to update (master by default)
  base_url:  https://intriguing-break-7p66rwu47u.glitch.me

show_preview_links: false
publish_mode: editorial_workflow
open_authoring: true


# This line should *not* be indented
media_folder: "uploads" # Media files will be stored in the repo under /uploads
public_folder: "/uploads"

collections:
  - name: "chapters" # Used in routes, e.g., /admin/collections/blog
    label: "Chapters" # Used in the UI
    label_singular: "Chapter"
    folder: "_chapters/" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    media_folder: "/uploads"
    public_folder: "/uploads"
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "chapter"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "header_feature_image", widget: "image", required: false}
      - {label: "Excerpt Finish", name: "excerpt_separator", widget: "hidden", default: "<!--do-not-remove-this-->"}
      - {label: "Chapter", name: "chapter", widget: "number", required: true, valueType: "int"}
      - {label: "Body", name: "body", widget: "markdown"}
